/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'institution' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const SubmitInquiryPayload = IDL.Record({
  'institution' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const SubmitResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'listInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'submitInquiry' : IDL.Func([SubmitInquiryPayload], [SubmitResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'institution' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const SubmitInquiryPayload = IDL.Record({
    'institution' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SubmitResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  
  return IDL.Service({
    'listInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'submitInquiry' : IDL.Func([SubmitInquiryPayload], [SubmitResult], []),
  });
};

export const init = ({ IDL }) => { return []; };